### ISSUE TITLE
The translation of 漢字

### ISSUE THREAD

**Issue by ethantw** [w3c/clreq#11]
In the document we use Hanzi for the translation of 漢字 at the time. Richard suggests we replace it with Han characters. Will edit it if no comments advise otherwise.

**Comment by lianghai** [comment]
Makes sense. "Han characters" is clear and conventional (in terms of multilingual technologies).

**Comment by hax** [comment]
Hanzi 的用法是要和  kanji （jlreq）和 hanja （klreq）对应嘛。

我特别看了一下，在日韩的排版需求里，kanji和hanja大体是作为ideographic character的简称。尤其是与所用的其他字符对应（日文里kanji和假名对应，韩文里hanja和谚文对应）。

由此简写的意图来看，han character 比 ideographic character 或 chinese character 省不了多少。因此我建议还是可以用 hanzi 的。

**Comment by upsuper** [comment]
GB12200.1-90 uses Hanzi as one of the translations of 汉字, the other one is Chinese character.

**Comment by lianghai** [comment]
那个「ideographic character」本身是个很糟糕的术语（语言学层面不正确），因为历史遗留和政治正确问题才依旧常常使用。
汉语书写系统的格局与日语、韩语不同，汉字与表音字母对立的情况并不存在。该文档中实际上也没有简写此类术语的必要。
中译英领域没有大量使用转写（拼音）的习惯，这和日语、韩语不一样。孤零零一个「hanzi」加大阅读门槛（并没有 kanji、hanja、kana、hangul 之类来与之并举），而且这种转写词不易入文（比如复数变形不管变不变都很别扭）。
在我看来，用「hanzi」的唯一价值就是比较简短。但「Han character」或「Chinese character」较为平实。相比之下，「Chinese character」更为纯粹，而「Han character」这样的妥协结果仔细想想其实比较尴尬。
我这下更偏好「Chinese character」了。

**Comment by r12a** [comment]
Unfortunately a separate thread has been running on this topic on the public-zhreq list.  
Please read the following (ordered chronologically to get around some issues we had with the archive)

chen zhuang https://lists.w3.org/Archives/Public/public-zhreq/2015Apr/0013.html
ishida   https://lists.w3.org/Archives/Public/public-zhreq/2015Apr/0000.html
li anqi  https://lists.w3.org/Archives/Public/public-zhreq/2015Apr/0001.html
xidorn https://lists.w3.org/Archives/Public/public-zhreq/2015Apr/0004.html
ishida https://lists.w3.org/Archives/Public/public-zhreq/2015Apr/0006.html
chen zhuang https://lists.w3.org/Archives/Public/public-zhreq/2015Apr/0012.html
mail from Eric Liu missing - working on fixing that - the text is included in the next link
ishida https://lists.w3.org/Archives/Public/public-zhreq/2015Apr/0010.html

**Comment by hax** [comment]
感谢提供链接，我引用其中比较重要的一条：

> In GB12200.1-90 Part 01, "汉字" is translated to "Chinese character, Hanzi".
> See 4.1.3.6 of that spec.

然后 Ishida 的意见是“hanzi”对于大多数非中文用户来说搞不清意思，不如用 han character 清晰。他也接受“chinese character”的译法。

我剩下的疑问是 kanji/hanja 除了与表音字母对立外是否有其他限制，比如不包含标点。“汉字”大多数人的理解中应该不包含标点符号。如果使用hanzi这个术语，我会做类同理解。而 han character 和 chinese character 的理解是如何的？另外目前我也不清楚在文档中我们是否需要这样限制性的概念？

**Comment by lianghai** [comment]
唉，「Chinese/han characters」当然不包括标点。没人会觉得它包含标点了……你现在有点把自己绕进去了。「某语 character」和「character」（编码技术的「字符」）概念是两回事。

**Comment by hax** [comment]
@lianghai 我主要是希望大家（特别是native english speakers）确认一下对这个东西的理解是否一致。另外就是这种理解在文档的具体语境里是否恰当（或者无关紧要）。

**Comment by ryukeikun** [comment]
其实我的倾向是，区别总集和子集的称呼。对于「CJKV统一汉字」这种人为的总集，使用 Han Character；而针对各个地区的子集，比如对于「日本汉字」或者日文编码里涉及到的汉字，可以用 kanji。因此，单纯针对 CLReq 这个文件来说，论述的对象是中文汉字，则多使用 Hanzi 这个词，和 JLReq 使用 kanji 一样。言外之意是，即使是同样一个汉字 Han Character，作为中国汉字 Hanzi 则是这个 CLReq 的处理对象，而如果到了日文语境作为 kanji 则遵守其他的需求和标准。

**Comment by lianqi** [comment]
read about this on Unicode website 
http://www.unicode.org/faq/han_cjk.html#17
Q: Why does Unicode use the term "ideograph" when it is linguistically incorrect?

A: The characters used to write Chinese are traditionally called "Chinese characters" in the various East Asian languages (hanzi in Mandarin, kanji in Japanese and hanja in Korean). In English, they are generally referred to by names such as "ideograph" or "pictogram," even though these don't accurately reflect what the characters are or how they are used. Indeed, no single linguistic term adequately describes these characters because they have such varied origins and uses. The only possible exception would be "sinogram," which is Latin for "Chinese character" and rarely found.

Unicode originally adopted the word "ideograph" as representing common English usage. The term is now so pervasive in the standard that it cannot be abandoned.

**Comment by lianqi** [comment]
read about this on Unicode website 
http://www.unicode.org/faq/han_cjk.html#17
Q: Why does Unicode use the term "ideograph" when it is linguistically incorrect?

A: The characters used to write Chinese are traditionally called "Chinese characters" in the various East Asian languages (hanzi in Mandarin, kanji in Japanese and hanja in Korean). In English, they are generally referred to by names such as "ideograph" or "pictogram," even though these don't accurately reflect what the characters are or how they are used. Indeed, no single linguistic term adequately describes these characters because they have such varied origins and uses. The only possible exception would be "sinogram," which is Latin for "Chinese character" and rarely found.

Unicode originally adopted the word "ideograph" as representing common English usage. The term is now so pervasive in the standard that it cannot be abandoned.

**Comment by hax** [comment]
话说此issue close掉的最后决定是啥？
