### ISSUE TITLE
Translate the glossary

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#163]
We should finish the English translation of the glossary. The untranslated items are:

* ~~標號~~
* ~~齊頭尾對齊~~
* ~~全形/全角~~
* ~~入聲~~
* ~~聲調~~
* ~~聲母~~
* ~~宋體（明體／明朝體）~~
* ~~天／天頭~~
* None 🎉

(I will edit this post as the terms are translated.)

**Comment by ryukeikun** [comment]
the current translations should be reviewed, especially for the terms that are paired, e.g.
天/地
全角/半角
标号/点号
声母/韵母

**Comment by xfq** [comment]
I'll list the current translation of the terms that are paired below, for ease of review:

-----

天：The top margin between the top edge of a trimmed page and the type area.

地：The bottom margin between the edge of a trimmed page and the type area.

-----

全角：Relative index for the length which is equal to a given character size, or the sqare character frame which character advance that is equal to character size.

半角：Character frame which has a character advance of a half em.

*xfq's note: whether to use Em/En as aliases of fullwidth/halfwidth is still under discussion.*

-----

标号：Puctuation marks for indication, mainly for marking the special nature and function of a part (mainly words) of a sentence.

点号：Punctuation marks for breaking, mainly for pause and mood, including marks at end-sentence and in-sentence.

-----

声母：The initial consonants of Chinese syllable.

韵母：The part in a Chinese syllable without initial and tone.

-----

繁体中文：A family of Chinese characters that are relatively more complex in structure and stroke count. They are known as Traditional Chinese because of their long history of use, while their less complex counterparts are known as Simplified Chinese.

简体中文：The writing system using simplified forms, glyphs and less strokes of Chinese Character, mainly refer to Jianhuazi (Simplified Character) published and revised in 1960s in Chinese mainland. Cf. Traditional Chinese.

-----

孤行：When the start of a page contains a single line of text that is the last line of a paragraph from the previous page, that line is known as a widow.

孤字：When a paragraph of text ends with a line that contains only a single character, with or without punctuation, that character is known as an orphan.

-----

Also the four main typefaces (I'm wondering if we really need to include these in the glossary, since it's already in the document):

宋体：A major style of Chinese typeface, in which horizontal lines are thin and vertical lines are thick, and decorative parts at the start and the end of a stroke, representing press of brush. Similar to "serif" of Western typography.

楷体：The regular or model script of Chinese handwriting, and also the traditional printing type style base on the same.

黑体：A script with minimal line contrast in character strokes and is one of the traditional scripts used in Chinese printing.

仿宋体：An elegant and upright script that combines the characteristics of Song and Kai and is one of the traditional scripts used in Chinese printing.

-----

**Edit: Sorry, I missed "底端/顶端" and "横排/直排".**

底端：The closing side of the content in a type area. Usually, for vertical writing, it is on the left side while for horizontal writing, it is in the bottom.

顶端：The beginning side of the content in a type area. Usually, for vertical writing, it is on the right side while for horizontal writing, it is in the upper side.

横排：The process or the result of arranging characters on a line from left to right, of lines on a page from top to bottom, and/or of columns on a page from left to right.

直排：The process of arranging characters on a line from top to bottom, of lines on a page from right to left.

**Comment by ryukeikun** [comment]
In my view:

1. The edited version of 天/地 are good now.

2. There are a typo and some grammatical problem in 全角 definition, I think it is better to change like this to make it clear:

全角：a) A relative index for the length which is equal to a given character size. b) A square character frame that has a character advance of character size.

半角：a) A relative index for the length which is equal to 1/2 of a given character size. b) A square character frame that has a character advance of 1/2 character size.

I think the concept of em/en is always the same in western and east-Asian typography.  If it is not a consensus yet, can be deleted from this version and be discussed further more for next version.

3. The edited version of 标号/点号 are good now.

4. Better English for 声母 should be：The initial consonant of a Chinese syllable. (The modern Chinese has no consonant clusters, so no need to make it as plural)

5. My version of approved definitions:

繁体中文：The writing system of Chinese using characters that are relatively more complex in structure and stroke count. Known as Traditional Chinese because of its long history of use. Cf. Simplified Chinese.

简体中文：The writing system of Chinese using characters that are relatively simpler in structure and stroke count, mainly refer to Jianhuazi (Simplified Character) published and revised in 1960s in Chinese mainland. Cf. Traditional Chinese.

6.
孤行：literally "orphan-line", the paragraph-ending line that falls at the beginning of a new page or column, or the paragraph-opening line that appears by itself at the end of a page or column; both separated from the rest of the text. 

孤字：literally "orphan-character", the paragraph-ending single character, with or without punctuation, became the last line of a paragraph.

It is important to cut off the relations with widow/orphan in western typography because the details are not exactly the same. e.g. according to the definitions of the Chicago Manual of Style, both Widow and Orphan are 孤行, but no terms refer to 孤字. There are even some more different definitions in other system. In this situation, there is no benefit to connect those western concepts with Chinese layout, that will make more confusion and misunderstanding. Keep 孤行/孤字 as special terms for CLREQ is better. 

7. The four main typefaces are not needed for glossary in my point of view.

**Comment by ethantw** [comment]
Chinese mainland should be Mainland China for the sake of consistency.

**Comment by xfq** [comment]
Thanks for your comments, @ryukeikun and @ethantw! Addressed in https://github.com/w3c/clreq/commit/73eeff458869e3e4101ac8cdacf5d2b225af57b7 with minor adjustment.

**Comment by xfq** [comment]
Closing. Future discussions can happen in new issues.
