### ISSUE TITLE
Please review: 3.1.3.3 Locale specified rules for punctuations

### ISSUE THREAD

**Issue by bobbytung** [w3c/clreq#177]
I just add a section in 3.1.3 to describe rules for punctuations in vertical writing in Mainland China. 

https://w3c.github.io/clreq/#atypical_punctuation_marks_and_their_arrangements

@ryukeikun 你能看看這樣的編排是否恰當，此外，我發現Apple的系統字體，無論蘋方還是宋體，分號（；）在竪排的位置都是錯誤的

@xfq @lianqi Please help me to review English translations

**Comment by jjgod** [comment]
> 此外，我發現Apple的系統字體，無論蘋方還是宋體，分號（；）在竪排的位置都是錯誤的

Can you elaborate? I just tried a test with TextEdit it seems to work as expected:

![screen shot 2018-05-27 at 12 48 48](https://user-images.githubusercontent.com/1017/40589996-6f5f7bd6-61ac-11e8-8943-6894297da535.png)

**Comment by xfq** [comment]
> @xfq @lianqi Please help me to review English translations

Submitted #178.

**Comment by bobbytung** [comment]
@jjgod 

You are right. It should be a safari's bug.

<img width="505" alt="2018-05-28 4 45 01" src="https://user-images.githubusercontent.com/1863378/40606016-a073cfe8-6296-11e8-9d3a-2f75380e5e3b.png">

**Comment by r12a** [comment]
@bobbytung i just took a closer look at the section, and here are some notes for you or for the person who translated to English.

[1]
perhaps the class=checkme should now be removed from the section tag?

[2]
> Publications in Mainland China rarely use vertical writing mode. But there are still ancient books in Traditional Chinese and some books in Simplified Chinese that utilise vertical writing mode.

 Are we talking about ancient books specifically in Mainland China here?  It's not clear from the text. It might help to change the full stop before 'But' to a comma and say 'there are still ancient books there in'.

I wasn't completely sure whether we are talking about typesetting of old books in Mainland China (which were presumably in TC) as well as modern text that is vertically set (given the emphasis on region being important, rather than SC/TC).  Could you clarify that for me?

[3] 
> For such books, punctuation layout should follow the rules in General Rules for Punctuation (GB/T 15834-2011). The rules should be applied based on place of publication, not based on whether the content is Traditional/Simplified Chinese.

It would be useful to have a link on the GRP title. However, i'm not clear what those rules are: are they the rules we describe in this document?  It sounds to me from the following sentence like the GPR contains different rules for different regions. Is that correct?

[4] 
> Rules differing from Simplified Chinese punctuation are as follows:

I'm a bit unclear here. Are you describing how rules for vertical text in SC are different from those for horizontal text in SC as described in this document? If so, that seems to indicate that the sentence:

> Rules identical to Traditional Chinese punctuation are as follows:

might be clearer if it said:

"Rules for vertical text in Mainland China that are identical to the rules for vertical Traditional Chinese text as described in this document."

If i understood correctly, it would probably make it much clearer for the reader to change the title of the subsection to "Region-specific punctuation rules for vertical text in Mainland China".  

hope that helps

**Comment by ryukeikun** [comment]
I have rewrote this section, deleted some repeated contents, and combined some general rules into 3.1.2.
