### ISSUE TITLE
Need to add details on Line Adjustment

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#255]
Need to add details on Line Adjustment as [JLReq §3.8](https://www.w3.org/TR/jlreq/#line_adjustment), especially the procedures for reduction and expansion of inter-character space.

CLReq do not need to mention every details as JLReq do, but at least need some guidelines for UA to follow.

**Comment by ryukeikun** [comment]
参照 JLReq 3.8.3 和 3.8.4，

建议中文行内调整时按照下述步骤，寻找挤压的优先顺序：

1. 西文词距。若有多个需要均等挤压，最小可以挤到四分。
2. 行末标点。若有全宽的挤为二分。
3. 行内间隔号。如果行内间隔号为全宽，带有前后的四分空，则必须前后同时挤，最小挤到0，即间隔号为全宽的挤为二分
4. 行内引号和括号。开始括号的前侧、结束括号的后侧、逗号后侧的二分空，最小挤为二分。
5. 行内逗号、顿号、分号。后侧的二分空，最小挤为二分。
6. 行内的句号、问号、感叹号。后侧的二分空，最小挤为二分。
7. 行内的中西间距，从默认的四分空前后同时挤，最小挤为八分空。

建议中文行内调整时按照下述步骤，寻找拉伸的优先顺序：
1. 西文词距。若有多个需要均等挤压，最大可以拉伸二分。
2. 行内的中西间距，从默认的四分空前后同时拉，最大可拉大到二分空。
3. 除去特别被禁止分离的字符之外，均匀拉伸。

**Comment by xfq** [comment]
We can add an entry for line adjustment in the Glossary too.

**Comment by xfq** [comment]
Related: https://github.com/w3c/clreq/issues/278

**Comment by xfq** [comment]
我们是否需要说明行内调整的必要性？

类似于jlreq的§ 3.8.1: https://w3c.github.io/jlreq/#necessity_for_line_adjustment

**Comment by xfq** [comment]
另外，以下是对 https://github.com/w3c/clreq/issues/255#issuecomment-586071816 评论的两点问题：

1. 是否需要定义或者解释一下「均等挤压」和「均匀拉伸」？
2. 关于「行末标点」，是否需要具体说明是哪些标点？

**Comment by ryukeikun** [comment]
> 我们是否需要说明行内调整的必要性？
> 
> 类似于jlreq的§ 3.8.1: https://w3c.github.io/jlreq/#necessity_for_line_adjustment

这就等于重写这一小结了。可以改成这样：

> 1. 行内调整的必要性
> 由于避头尾等原因造成行的长度长短不一时，需要进行行内调整。针对整个段落的字符串，除去「禁止分开」的地方以 外进行分割，排列成行。除了段落最后一行以外的各行行首、行尾必须放到指定行长的行首、行尾位置。对于段落的最后一行，按照排版风格进行标点宽度调整即可，字符串末尾没有必要与指定行长的行尾对齐。

> 造成需要行内调整的原因有很多，主要有：
> a. 行内夹杂了阿拉伯数字、西文等非全角字符
> b. 有标点符号连续出现，且按照原则性调整之后依旧不是整数倍
> c. 行内混用不同字号
> d. 标点符号避头尾处理

**Comment by huijing** [comment]
你们还会再修改吗？就翻译这个版本？

**Comment by huijing** [comment]
我试试看翻译以上那一段：

1.  The Necessity for Line Adjustment
Line breaking rules for Chinese characters may result in uneven line lengths, which require adjustment. Within a run of characters, aside from positions where characters are "unbreakable", line breaks may occur for the text to be arranged into rows. Other than the last line of a paragraph, the start and end of a line must be placed at the specified line start and line end position respectively. The last line of the paragraph will be adjusted accordingly to the overall flow of the text with adjustments made to the width of its punctuation. It is not necessary for the end of the last line to be aligned with the rest of the text.

There are a number of scenarios which require line adjustment, mainly:
a. Lines which are interpersed with many European numerals, Latin letters or other non-full width characters
b. Instances where punctuation marks occur consecutively and still remain uneven after principle-based(?) adjustments
c. Lines containing characters of different font sizes
d. The processing of line prohibition rules for punctuation

**Comment by ryukeikun** [comment]
As discussed in last editor meeting via Skype, I am now rewriting this part as following:

> 3.5 行内调整 Line Adjustment
> 3.5.1 行内调整的必要性 Necessity for Line Adjustment
> 由于「3.1.4 行首行尾禁则」等原因造成行的长度长短不一，这时需要进行「行内调整」。在除了「3.1.5 符号分离禁则」以外的的地方，先将整段文字按照指定的行长断开，排列成行。对于除了段落最后一行以外的各行，其行首、行尾必须分别放到指定行长的位置。对于段落最后一行，原则上按照排版风格进行标点宽度调整即可，末尾没有必要与指定行长的行尾对齐；最后一行需要调整的特殊情况，请参照 「3.4.4孤行与孤字处理」。而当段落有且仅有一行时，请参照 「3.4.3对齐处理」。
> 
> 造成需要行内调整的原因有很多，主要有：
> a. 行内夹杂了阿拉伯数字、西文等非一个汉字字宽的字符；
> b. 标点符号连续出现，且按照 「3.1.6.2 连续标点符号的调整」的原则性调整之后与事先设定的行长不一致；
> c. 行内混用不同字号，比如该行有「行内夹注」并使用了小一些的字号；
> d. 标点符号依照 「3.1.4 行首行尾禁则」进行了处理
> 
> 与西文排版不同，中文排版特别是书籍正文排版极少使用左齐右不齐，原则上应该进行两端对齐。西文排版两端对齐（justification）时，主要是调整单词之间的间隙（词距），而中文排版在两端对齐时，能调整的地方更多，具体如下所述。
> 
> 3.5.2 挤压处理和拉伸处理 Reduction and Addition of Inter-Character Spacing
> 行内调整的对象是需要按照预先定义的可调整空间，如西文词距、「3.1.6.1 标点符号的调整空间」等等。行内调整有以下两种方法：
> a. 挤压处理
> 「挤压处理」是指按照预先规定的排版风格，压缩西文词距、中西间距和「3.1.6.1 标点符号的调整空间」等处的做法。
> b. 拉伸处理
> 「拉伸处理」是指按照预先规定的排版风格，拉伸西文词距、中西间距以及其他未被特殊规定禁止调整等处的做法。
> 
> 出于紧凑易读、节约版面的思路，行内调整要遵循「先挤压、后拉伸」的原则，即应该先挤压处理，仍旧无法满足需求之后再进行拉伸处理。
> 
> 注释 NOTE：本文涉及到行内的「西文词距」调整，仅是针对「在中文排版内混排的西文」，因此，与纯西文排版的习惯不尽相同。一般的西文排版中的词距，需要依照所用字体、字号、字距进行不同判断，而且一般只拉伸、不挤压。
> 
> 3.5.3 挤压处理的优先顺序 Procedures for Inter-Character Spacing Reduction
> 行内调整的挤压处理，应该按照下述步骤，确定挤压的优先顺序后依次进行处理：
> 
> 1. 位于行末的标点。若有调整空间，则调成固定的半个汉字宽。（注释：行末的句号，在日文排版中往往不进行挤压处理。但是对于中文排版，一般要进行处理，这对于中国大陆的排版规范尤其重要。《GB/T 15834-2011 标点符号用法》有明确规定「5.1.10 标点符号排在一行末尾时，若为全角字符则应占半角字符的宽度（即半个字位置），以使视觉效果更美观。」）
> 2. 位于行内的西文词距。一行内若有多处西文词距，应该同时、同等量处理，每个西文词距最小可以挤压到四分之一汉字宽。
> 3. 位于行内的间隔号。挤压时必须同时从字面两侧、同等量处理，最小挤到0，即变成半个汉字字宽。
> 4. 位于行内的夹注符号。可以对开始夹注符号的前侧、结束夹注符号的后侧进行挤压。一行内如有多处，应该同时、同等量处理，最小可以挤压到半个汉字字宽。
> 5. 位于行内的逗号、顿号、分号。挤压空间依照「3.1.6.1 标点符号的调整空间」，可以是后侧，也可以是字面两侧同时。一行内如有多处，应该同时、同等量处理，最小可以挤压到半个汉字字宽。
> 6.  行内的中西间距。一行内若有多处，应该同时、同等量处理，最小挤为八分之一汉字宽。（注释：在一些排版风格中，中西间距固定默认宽度[如四分之一汉字宽]，被排除在行内调整对象之外，不允许被挤压。）
> 7. 位于行内的句号、问号、感叹号。依照「3.1.6.1 标点符号的调整空间」，如果有调整空间则可以挤压，最小挤为半个汉字字宽。（注释：由于句末标点表示停顿较大，因此有些排版风格禁止此项调整，而保持句号、问号、感叹号固定一个字宽。）
> 
> 3.5.4 拉伸处理的优先顺序
> 
> 行内调整的拉伸处理，应该按照下述步骤，确定拉伸的优先顺序后依次进行处理：
> 
> 1. 西文词距。一行内若有多处西文词距，应该同时、同等量处理，每个西文词距最大可以拉伸到半个汉字字宽。
> 2. 行内的中西间距，从默认宽度[如四分之一汉字宽]开始拉伸，一行内若有多处，应该同时、同等量处理，最大可拉大到半个汉字字宽。（注释：很多排版风格在实际处理上，只允许最大拉伸到三分之一汉字宽。与上述挤压处理一样，在一些排版风格中，中西间距固定默认宽度[如四分之一汉字宽]，被排除在行内调整对象之外，不允许被拉伸。）
> 3. 若上述所有项目均无法调整，则只能针对剩余所有字符间距，进行同时、同等量拉伸，但是：
>  	a. 禁止对「3.1.5 符号分离禁则」规定的字间距进行拉伸处理
>  	b. 尽量避免对连接号、分隔号与其前后的字符进行拉伸处理

**Comment by xfq** [comment]
> d. 标点符号依照 「3.1.4 行首行尾禁则」进行了处理

这里应该是「3.1.4 行首行尾禁则」和「3.1.5 符号分离禁则」？

-----

> 挤压处理的优先顺序

这里的顺序和之前不一样了，从

1. 西文词距
1. 行末标点
1. 行内间隔号
1. 行内引号和括号
1. 行内逗号、顿号、分号
1. 行内的句号、问号、感叹号
1. 行内的中西间距

变成了：

1. 行末标点
1. 西文词距
1. 行内间隔号
1. 行内的夹注符号
1. 行内的逗号、顿号、分号
1. 行内的中西间距
1. 行内的句号、问号、感叹号

是什么原因？

-----

另外，我们是否需要添加一些（包含网格的）图？

**Comment by ryukeikun** [comment]
> 这里应该是「3.1.4 行首行尾禁则」和「3.1.5 符号分离禁则」？

可以写，也可以不写。这里并不是穷尽列举。

> 这里的顺序和之前不一样了

是的。把行末标点的优先级提高，这是符合「先固定行首行末，在调行中」的逻辑，而且也针对GB符合性，提高行末标点的重要级别；而对于「行内的句号、问号、感叹号」，正如注释所说，很多出版风格里这都是固定不能调的（在 JIS 也是如此），如果要调，重要级别应该最低。

> 另外，我们是否需要添加一些（包含网格的）图？

图可以加，但是行内调整是一个动态的过程，似乎优先顺序很难用图展示？等文本确定之后再说吧。要加图的地方有很多呢。

**Comment by huijing** [comment]
First draft of translation is as follows:

3.5 Line Adjustment 行内调整 

3.5.1 Necessity for Line Adjustment 行内调整的必要性 

There are numerous reasons, e.g. 3.1.4 Prohibition Rules for Line Start and Line End , that result in line lengths being uneven. Under such circumstances, line adjustment is required. With the exception of 3.1.5 Prohibition Rules for Unbreakable Marks, a run of text may be broken at the specified line length, allowing the text to be arranged into even rows.  Other than the last line of a paragraph, the start and end of a line must be placed at the specified line start and line end position respectively. The last line of the paragraph will be adjusted accordingly to the overall flow of the text with adjustments made to the width of its punctuation. It is not necessary for the end of the last line to be aligned with the rest of the text. Please refer to 3.4.4 Handling of Widows and Orphans. If the text only comprises of 1 line, please refer to 3.4.3 Line Alignment Processing.

由于「3.1.4 行首行尾禁则」等原因造成行的长度长短不一，这时需要进行「行内调整」。在除了「3.1.5 符号分离禁则」以外的的地方，先将整段文字按照指定的行长断开，排列成行。对于除了段落最后一行以外的各行，其行首、行尾必须分别放到指定行长的位置。对于段落最后一行，原则上按照排版风格进行标点宽度调整即可，末尾没有必要与指定行长的行尾对齐；最后一行需要调整的特殊情况，请参照 「3.4.4孤行与孤字处理」。而当段落有且仅有一行时，请参照 「3.4.3对齐处理」。

There are a number of reasons for line adjustment, mainly:
    a. Lines which are interspersed with many European numerals, Latin letters or other non-full width characters
    b. Instances where punctuation marks occur consecutively and still remain uneven after 3.1.6.2 Adjustment of adjacent punctuation marks
    c. Lines containing characters of different font sizes
    d. After the processing of punctuation in accordance with 3.1.4 Prohibition Rules for Line Start and Line End

造成需要行内调整的原因有很多，主要有：
a. 行内夹杂了阿拉伯数字、西文等非一个汉字字宽的字符；
b. 标点符号连续出现，且按照 「3.1.6.2 连续标点符号的调整」的原则性调整之后与事先设定的行长不一致；
c. 行内混用不同字号，比如该行有「行内夹注」并使用了小一些的字号；
d. 标点符号依照 「3.1.4 行首行尾禁则」进行了处理

In contrast to Western typesetting, the body text in Chinese books are rarely left-aligned, and instead should be justified. Justification of Western texts hinges on the adjustment of space between the words on a line, whereas there are more options for line justification when it comes to Chinese typesetting.

与西文排版不同，中文排版特别是书籍正文排版极少使用左齐右不齐，原则上应该进行两端对齐。西文排版两端对齐（justification）时，主要是调整单词之间的间隙（词距），而中文排版在两端对齐时，能调整的地方更多，具体如下所述。

3.5.2 Reduction and Addition of Inter-Character Spacing 挤压处理和拉伸处理

Line adjustments are predicated upon the amount of available space, for example, spacing between Western words, 3.1.6 Punctuation Width Adjustment, and so on. There are two methods for line adjustment:
  a. Reduction of Inter-Character Spacing
  Inter-character spacing like those between Western words, mixed texts, or as described in 3.1.6.1 Punctuation Adjustment Space, should be reduced in accordance to the prevailing typesetting style.
  b. Addition of Inter-Character Spacing
  Inter-character spacing like those between Western words, mixed texts or scenarios that are not limited by prohibition rules should be added in accordance to the prevailing typesetting style.

行内调整的对象是需要按照预先定义的可调整空间，如西文词距、「3.1.6.1 标点符号的调整空间」等等。行内调整有以下两种方法：
  a. 挤压处理
  「挤压处理」是指按照预先规定的排版风格，压缩西文词距、中西间距和「3.1.6.1 标点符号的调整空间」等处的做法。
  b. 拉伸处理
  「拉伸处理」是指按照预先规定的排版风格，拉伸西文词距、中西间距以及其他未被特殊规定禁止调整等处的做法。

In order to make the composition tighter and more readable, the guiding principle is to attempt to implement space reduction first. In the event that is insufficient, then space can be added where acceptable to achieve justification.

出于紧凑易读、节约版面的思路，行内调整要遵循「先挤压、后拉伸」的原则，即应该先挤压处理，仍旧无法满足需求之后再进行拉伸处理。

Note: the word spacing in Western texts described here only pertains to situations which involve compositions of mixed Western and Han characters. The expected behaviour is different from that for purely Western texts, which will take into account the typeface, font size and letter spacing when doing text justification. In general, Western texts will add to word spacing and rarely uses space reduction.

注释 NOTE：本文涉及到行内的「西文词距」调整，仅是针对「在中文排版内混排的西文」，因此，与纯西文排版的习惯不尽相同。一般的西文排版中的词距，需要依照所用字体、字号、字距进行不同判断，而且一般只拉伸、不挤压。

3.5.3 Procedures for Inter-Character Spacing Reduction 挤压处理的优先顺序

Inter-Character Spacing Reduction should be processed according to the following steps, in order of precedence:

行内调整的挤压处理，应该按照下述步骤，确定挤压的优先顺序后依次进行处理：

1. At the end of a line: adjusted to fixed half a character width. (Note: In Japanese texts, periods at the end of a line typically do not have their space reduced, but Chinese texts do. This is especially important in Mainland China where the General Rules for Punctuation (GB/T 15834–2011) defines in 5.1.10 that if a full-width punctuation occurs at the end of a line, it should take up half a character width for a more pleasing aesthetic)

位于行末的标点。调成固定的半个汉字宽。（注释：行末的句号，在日文排版中往往不进行挤压处理。但是对于中文排版，一般要进行处理，这对于中国大陆的排版规范尤其重要。《GB/T 15834-2011 标点符号用法》有明确规定「5.1.10 标点符号排在一行末尾时，若为全角字符则应占半角字符的宽度（即半个字位置），以使视觉效果更美观。」）

2. Spacing between Western texts: for lines with numerous instances of Western text, their spacing should be processed at the same time, with equal treatment. The minimum space between each Western text should be quarter of a character width.

位于行内的西文词距。一行内若有多处西文词距，应该同时、同等量处理，每个西文词距最小可以挤压到四分之一汉字宽。

3. Interpuncts: space reduction must take place equally on both sides of the character. The minimum space is 0, whereby the interpunct ends up being half a character width.

位于行内的间隔号。挤压时必须同时从字面两侧、同等量处理，最小挤到0，即变成半个汉字字宽。

4. Brackets: space reduction can take place before the opening bracket and after the closing bracket. If multiple brackets occur within the same line, their space reduction should be processed at the same time, with equal treatment. Space can be reduced until the bracket is half a character width.

位于行内的夹注符号。可以对开始夹注符号的前侧、结束夹注符号的后侧进行挤压，最小可以挤压到半个汉字字宽。一行内如有多处，应该同时、同等量处理。

5. Commas, secondary commas and semi-colons: space reduction should follow 3.1.6.1 Punctuation Width Adjustment. Spacing can be reduced at the end of the punctuation mark or equally on either side. If multiple of such punctuations occur within the same line, their space reduction should be processed at the same time, with equal treatment. Space can be reduced until the punctuation mark is half a character width.

位于行内的逗号、顿号、分号。挤压空间依照「3.1.6.1 标点符号的调整空间」，可以是后侧，也可以是字面两侧同时，最小可以挤压到半个汉字字宽。一行内如有多处，应该同时、同等量处理。

6. Spacing between Han characters and Western texts: if there are numerous instances of mixed texts, space reduction should be processed at the same time, with equal treatment, with the minimum space being one-eighth of a character width. (Note: Certain typesetting styles have a fixed default spacing between Han characters and Western texts, for example a quarter of a character width, in such cases, adjustment is not allowed.)

行内的中西间距，最小挤为八分之一汉字宽。一行内若有多处，应该同时、同等量处理。（注释：在一些排版风格中，中西间距固定默认宽度[如四分之一汉字宽]，被排除在行内调整对象之外，不允许被挤压。）

7. Periods, question marks and exclamation marks: in accordance to 3.1.6.1 Punctuation Width Adjustment, if there is available space, spacing can be reduced up until the minimum size of half a character width. (Note: as these punctuation marks indicate a longer pause at the end of a sentence, certain typesetting styles do not allow line adjustment to be made on them, maintaining their width to be one character width.)

位于行内的句号、问号、感叹号。依照「3.1.6.1 标点符号的调整空间」，如果有调整空间则可以挤压，最小挤为半个汉字字宽。（注释：由于句末标点表示停顿较大，因此有些排版风格禁止此项调整，而保持句号、问号、感叹号固定一个字宽。）

3.5.4 Procedures for Addition of Inter-Character Spacing 拉伸处理的优先顺序

Addition of Inter-Character Spacing should be processed according to the following steps, in order of precedence:

行内调整的拉伸处理，应该按照下述步骤，确定拉伸的优先顺序后依次进行处理：

1. Word spacing between Western texts: for lines with several Western word spaces, these should be processed at the same time, with equal treatment. Each word space can be expanded to a maximum of half a character width. 

西文词距。一行内若有多处西文词距，应该同时、同等量处理，每个西文词距最大可以拉伸到半个汉字字宽。

2. Space between Han characters and Western texts can be expanded from the default width (e.g. a quarter character width). They should be processed at the same time, with equal treatment. (Note: numerous typesetting styles practically only allow addition of space up to a third of a character width. Similar to space reduction, there are certain typesetting styles where the spacing between Han characters and Western texts are fixed at a default width, for example a quarter of a character width, in such cases, adjustments are not allowed.) 

行内的中西间距，从默认宽度[如四分之一汉字宽]开始拉伸，一行内若有多处，应该同时、同等量处理，最大可拉大到半个汉字字宽。（注释：很多排版风格在实际处理上，只允许最大拉伸到三分之一汉字宽。与上述挤压处理一样，在一些排版风格中，中西间距固定默认宽度[如四分之一汉字宽]，被排除在行内调整对象之外，不允许被拉伸。）

3. If all the aforementioned adjustments are not applicable, or the desired line length cannot be achieved, only the remaining inter-character spacing may be expanded at the same time, with equal treatment, to achieve text justification. However, there are two exceptions:
a. Spacing should not be added to characters stated in 3.1.5 Prohibition Rules for Unbreakable Marks 
b. Avoid adding spacing to connector marks, solidi and the characters immediately before and after these marks

若上述所有项目均无法调整，或调整之后依旧无法达到预设行长，则只能针对剩余所有字符间距，进行同时、同等量拉伸，但是：
a. 禁止对「3.1.5 符号分离禁则」规定的字间距进行拉伸处理
b. 避免对连接号、分隔号与其前后的字符进行拉伸处理

**Comment by xfq** [comment]
"Arabic numerals" should be changed to "European numerals". See https://w3c.github.io/clreq/#n035
