### ISSUE TITLE
Remove checkme/translateme/retranslateme when publishing to /TR?

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#303]
It is possible to remove the styling for the paragraphs marked as `checkme`, `translateme`, or `retranslateme` before publication (that is, they can only be shown in the [editor's draft](https://w3c.github.io/clreq/), but not the [/TR version](https://www.w3.org/TR/clreq/)). Is this useful?

(See also: https://github.com/w3c/simple-ruby/issues/28 )

**Comment by r12a** [comment]
No. Please don't. As discussed during the i18n telecon yesterday, the highlighting of such text provides useful cues to the reader, and avoids them raising spurious issues to complain.

The appropriate way to remove such highlighting from the TR version is to actually check or translate the items so that the markup can be removed.

**Comment by xfq** [comment]
OK. Closing this issue.
