### ISSUE TITLE
Change Figure for § 3.3.5.2

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#330]
https://w3c.github.io/clreq/#h-ligatures

§ 3.3.5.2 is for ligature, but the current Figure 23 in this section contains no ligature, what it exactly showing is "positioning Zhuyin inline", which should be moved into section of "Inline annotations"

**Comment by upsuper** [comment]
Based on discussion on telecon, I'd suggest change this chapter title to "Multisyllabic characters", and make it clear that it's very rare. Also the figure indeed looks wrong. If we are going to add section for inline annotations, this may be used, but it's not a good example in this section.

**Comment by xfq** [comment]
Links to related discussions:

* https://www.w3.org/2020/09/16-clreq-minutes.html#t07
* https://www.w3.org/2020/10/14-clreq-minutes.html#t09

**Comment by xfq** [comment]
I did some archeological work and found that it has been in the document since [at least 2015](https://github.com/w3c/clreq/commit/f86e52f4287216ade52b939163fa37b7d9a8a33d#diff-dc3a7ff8f743ac6cc72294825f647e8f47529cdbfa138b012603d30db9b2ae5aR214-R220).

@ethantw Do you know the background and intention of this section?

**Comment by xfq** [comment]
Removed this section in #345.
