### ISSUE TITLE
Adjustment of three or more adjacent punctuation marks

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#366]
https://w3c.github.io/clreq/#h-adjustment_of_adjacent_punctuation_marks

> The adjustment in principle should be: if two punctuation marks take 2 character widths, they should be reduced to 1.5 characters wide. Based on this principle, the typography style is allowed to be further adjusted so that the two punctuation marks take only 1 character width.

It is not clear here what is the principle for three or more adjacent punctuation marks, like:

```
“也许这就是‘生活的诗意’”（难道不是么）。
“也许这就是‘生活的诗意’！”（难道不是么）。
```

**Comment by realfish** [comment]
This adjustment rule could be interpreted that *any two adjacent* punctuation marks which take two Han character widths (2-em width) could collapse into one and a half Han character widths (1.5-em width) or less (1-em width).

For example, the punctuation cluster `’！”（` can be processed sequentially as three duplex group, i.e. `’！`, `！”`, and `”（`. Every the duplex group is so called “two adjacent punctuation marks”, which could be adjusted into 1.5-em width or even 1-em width depending on the typesetting style.

In my understanding, for the designing or typesetting workflow, the spacing of Chinese adjacent punctuation marks (so called 标点挤压) is generally processed partially between two marks rather than the overall group of multiple adjacent marks.

**Comment by realfish** [comment]
Btw, in practice, the 1.5-char-width adjustment covers most of the results of Chinese punctuation spacing. In my opinion, however, the number `1.5` or `1` here seems a little bit dogmatic. May we reword it by adding some theoretical derivation?

**Comment by ryukeikun** [comment]
As discussed in Monthly Editor meeting, and also explained by [realfish](https://github.com/realfish) mentioned above, this principle can be applied to _any two adjacent_ punctuation, but maybe we can explained it  a little more like this:
<img width="852" alt="any two adjacent" src="https://user-images.githubusercontent.com/8192599/118067145-f3d50b00-b3da-11eb-9a88-7d6a6cc04c8d.png">


So basically we only need to 1. find the adjacent punctuation group (in this example, there are 4 places, A, B, C and D ); 2. apply the "principle adjustment", and as we have mentioned that designer can do furthermore if they wish, so I don't think it is dogmatic. Maybe we can add some more explain in some other place to the 0.5/1/1.5/2 step logic in text setting of Chinese.

In practice, there are some furthermore styles for this adjustment when three or more adjacent gaps, e.g. 

1. In Plan II, the rule is set as: principle adjustment is 1.5 em (like for gap D), if the gap adjustment continues (like  ABC), then adjustment them all into 1 em;

2. In Plan I, the rule is set base one Plan II, but with a further rule: if the gap is between "trim-after" and  "trim-before" character (like C), even it is in the adjacent gap group (ABC), the adjustment should still set as 1.5 em. ( or, some programmer can also consider this is simply a accumulated result of 1.5em-adjustment rule when ABC gap is examined in text order)

Should we add such rules into CLReq? This is already in the range of typographic style rules.
