### ISSUE TITLE
关于「段首缩排」的英语表述

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#387]
[3.4.1](https://w3c.github.io/clreq/#line_head_indent_at_the_beginning_of_paragraphs) 的标题和正文，将「段首缩排」英译作「line head indent」可能不合适。段首缩排的常见英语表述是「(the/a) first-line indent / first-line indentation」。

Line head indent 可能会被误解作 the indent of (every) line (head)，后者更接近 [3.4.2](https://w3c.github.io/clreq/#line_head_indent_of_paragraphs) 中所说的「段落缩排」——也即行头侧的段落缩进（block/paragraph indent from the logical inline-start margin）。

**Comment by xfq** [comment]
The phrase "line head indent" comes from [jlreq](https://w3c.github.io/jlreq/#line_head_indent_at_the_beginning_of_paragraphs). It appeared in very early versions of jlreq like:

* [W3C Working Draft 11 April 2008](https://www.w3.org/TR/2008/WD-jlreq-20080411/#subheading1_5_3) (see Figure A1-14)
* [W3C Working Draft 15 October 2008](https://www.w3.org/TR/2008/WD-jlreq-20081015/#en-subheading2_5_1)

@r12a Do you have any suggestions on the terminology for indenting the first line of a paragraph?

**Comment by acli** [comment]
The normal way to say it in English is just “paragraph indent”, not “first-line indent” (and, as you point out, not “line head indent”, which makes no sense in English). See for example *The Elements of Typographic Style*, 4th ed., p. 40.

**Comment by realfish** [comment]
As I’ve mentioned [above](https://github.com/w3c/clreq/issues/387#issue-995454967), in the sense of digital typography, “a first-line indent(ation)” in English translates as “段**首**缩进/缩排” in Chinese while “a paragraph/block indent(ation)” translates as “**段落**缩进”.

In <i>CLReq</i>, a first-line indent translating as 段**首**缩进 indents the very first line of a paragraph (i.e., the beginning of a paragraph). On the other hand, a paragraph indent or a block indent, translating as **段落**缩进, indents the whole block of a paragraph from the margin sides. Considering that the “paragraph indent” may implicitly signify the notion of indenting the first line of a paragraph in certain unambiguous contexts, the term “block indent” is a better choice.

It’s important and necessary for <i>CLReq</i> to distinguish a first-line indent from a paragraph/block indent, since the reader of <i>CLReq</i> may use both the terms in near contexts or in the same context: for example, one “in-dents” the first line of a paragraph which is interrupted by a whole poetry extract / block quotation indented from the left and/or right margins, then “de-dents” the text after interruption (i.e., sets off text with no first-line indent).

In addition, there are some references according to which one can find the explicit wording of “first line indent / first-line indent”:

- [Pages User Guide for Mac](https://support.apple.com/guide/pages/set-paragraph-margins-tan92235a2d6/mac)
- [Microsoft Word Help](https://support.microsoft.com/en-us/office/indent-the-first-line-of-a-paragraph-b3721167-e1c8-40c3-8a97-3f046fc72d6d)
- [Adobe InDesign Help](https://helpx.adobe.com/indesign/using/tabs-indents.html)
- [CMOS](https://www.chicagomanualofstyle.org/book/ed17/part1/ch02/psec012.html)
- [Butterick’s Practical Typography](https://practicaltypography.com/first-line-indents.html)
- [Wikipedia “Indentation (typesetting)”](https://en.wikipedia.org/wiki/Indentation_(typesetting))

**Comment by acli** [comment]
Excuse my bluntness, @realfish, but Chicago gets a lot typography wrong (if you asked any well-informed North American designer which is more authoritative, Chicago or Bringhurst, the answer you’ll get is Bringhurst is always more authoritative). Same with APA. Or Microsoft Word (try mentioning Microsoft Word to an experienced book designer – I’m not talking about myself – all you’ll get is “Microsoft Word is not a page layout program”).

But if we *have* to use “first-line indent”, I’m not going to argue with you. It at least makes sense; “paragraph head indent” is absolutely meaningless in English.

Just don’t pretend that we’re using “professional design language”. We’re not.

**Comment by acli** [comment]
BTW, I have to add that Wikipedia is a very poor source for typographical terms; I literally got into an edit war a decade ago, I know how bad they are.

**Comment by realfish** [comment]
I just present some usages de facto of the term “first-line indent”. As for the @acli’s question to some references’ authority, I have no comment. In my position, I treat neither the ETS nor CMOS (seems you gave low-rating to CMOS) as a prior authority than others. I hope this clarifies.

**Comment by acli** [comment]
@realfish FWIW, even from a LaTeX user POV Chicago is inaccurate; Chicago is designed for copy editors, not designers (if this isn’t clear, copy editors and designers don’t always use the same terms). You’ll just need to read their chapter on XML if you want to also give it a “low-rating” yourself, in your own words.

Also, I have never heard anyone call it ETS. It’s Bringhurst if you want a short name.

**Comment by ryukeikun** [comment]
Checking with JLReq, 段首缩排 is expressed _Line Head Indent at the Beginning of Paragraphs_ in [3.5.1](https://www.w3.org/TR/jlreq/#line_head_indent_at_the_beginning_of_paragraphs), while 段落缩进 is simply expressed as _line head indent_ as in [3.5.2](https://www.w3.org/TR/jlreq/#line_head_indent_and_line_end_indent). 

Accordingly, in CLReq, the subtitle of [3.4.1](https://w3c.github.io/clreq/#line_head_indent_at_the_beginning_of_paragraphs) is also expressed _Line Head Indent at the Beginning of Paragraphs_, as 段首 is clearly express as _at the Beginning of Paragraphs_, although a little long-winded, it is OK for me.

And in JLReq, it is necessary to say _line head_ indent （字下げ）because they use also _line end_ indent（字上げ）, which is not mentioned in CLReq but maybe we need to add it as 行尾缩进, but this will be another issue.

**Comment by acli** [comment]
In that case I’ll get this fixed in JLReq. Thank you @ryukeikun

**Comment by realfish** [comment]
The term “line head/end indent” is rational in the context of paragraph/block indent(ation).

However, if <i>CLReq</i> treats “indentation at the beginning of paragraphs” as a noteworthy section/sub-chapter, the concise form of “first-line indent” should be a better option for referring to the specific indent. In this context, the obverse/counterpart of first-line indent which is noted as “tupai 凸排” now, could be reworded into the “hanging indent” or neologism “(first-line) outdent”.

**Comment by acli** [comment]
Look, I’m not against inventing new terms, per se; but if we claim to use “professional design language” (as is claimed in another thread), I need to point out that this is not professional design language. “Line head indent” isn’t even copy editing language. It might be “rational” from a computer science POV but no one will understand it.

If we start to really invent new terms we might as well create a W3C style guide so that every single document – including the normal CSS standards – will use those new terms, and use them consistently. And provide a disclaimer that these are W3C-specific terms and we make no effort in harmonizing them with traditional typography, graphic design, or copy editing practices.

**Comment by ryukeikun** [comment]
The point @realfish talking about is the structure of this section, and the point @acli talking about is about usage of new terms, both of which are already a little away from original purpose of this issue.

Anyway, what I could say is, current CLReq structure is made base on JLReq, while JLReq structure is base on JIS X 4051. As a matter of fact, first-line indent is quite more frequent and important (which can be seen in almost every document) than paragraph-indent (which can mostly only be seen for quotation), that is the reason both of these 2 Japanese document state deal with it firstly. 

For CLReq, there is no necessary to match every section with JLReq. What we only need to discuss is, whether to make the structure of this document according to usage frequency (as Japanese ones) or more logical structure (as @realfish advised). 

And about the usage of new terms, as my personally opinion, we should try to avoid make/use new terms as much as we can, especially in such a _requirement_ document. What we need to do in this document is, e.g. showing there is a term called "hanging indent" in publishing world (“professional design language”) and explain it to engineers and technicians, instead of making a term such as "outdent/dedent". However, some issues that @acli mentioned are not in this case but for the translation. _Line head/end indent_ maybe a little odd in English, but they are easy to understand and used simply as translation of Japanese terms of 字下げ/字上げ , which are considered necessary when JLReq is written.

**Comment by realfish** [comment]
My intention of this issue is always a translation advice for the Chinese term 段**首**缩进. In short, I advise to change the “line head indent at the beginning of paragraphs” into the “first-line indent(ation)”. In this sense, or in this issue, I haven’t advise for the translation about **段落**缩进, which is better to be discussed under a new issue . 

In addition, I tried to supplement some statements for the necessity to distinguish the term “first-line indent” from “paragraph/block indent” (the term “paragraph indent” here is used as-is according to the current <i>CLReq</i>). The related references were only presented to rationalize the term “first-line indent” itself.

As for the mention of <i>CLReq</i>’s doc structure, it was supposed to present the status quo that the <i>CLReq</i> has already treated the “段首缩进” as a noteworthy section. Based on the doc status quo, a set of concise terms which maps the concepts/notions related to the “段首缩进” should be taken into account.

Hope this clarifies.

**Comment by acli** [comment]
In English, “paragraph indent” means first-line indent, and this is why I was citing Bringhurst. Block indent is block indent; paragraph indent is paragraph indent.

We might want to avoid “paragraph indent” because it might confuse some readers, but “paragraph/block indent” is incorrect because they are two completely different things.

**Comment by acli** [comment]
BTW, “outdent” (as a verb) is already an accepted term. It appears in Bringhurst (p. 40), for example.

**Comment by xfq** [comment]
We changed “line head indent at the beginning of paragraph(s)” to “first-line indent(s)”. Closing this issue.
