### ISSUE TITLE
It’s difficult to switch languages on mobile

### ISSUE THREAD

**Issue by xfq** [w3c/clreq#414]
I tried a few mobile phones, and I couldn’t see the buttons to switch languages without scrolling to the right. Maybe we should put them at the top of the page on mobile.

**Comment by huijing** [comment]
I dug into the issue and this is happening because down the bottom of our document, the tables (used for glossary etc.) are wider than the width of the viewport. The language switcher is getting pushed outside the viewport width because of that.
We could make the parent container of the tables to have horizontal overflow, so just the tables need to be scrolled, not the whole page (I tried it with devtools and not the actual code so I'm not sure if this is work to fix all mobile device issues).

**Comment by xfq** [comment]
Looks like a way to fix this indeed, @huijing. Would you like to send a PR for it?

-----

BTW, I just made an unfinished prototype page here, trying to put the buttons at the top of the page (on narrow screens): https://xfq.github.io/testing/clreq-mobile/

**Comment by huijing** [comment]
Okay. Will open PR.
How do you do the preview version?

**Comment by xfq** [comment]
> Okay. Will open PR. How do you do the preview version?

I paste the URL of the page on GitHub here: https://raw.githack.com/ , and the "Use this URL for development" link is the preview link.
