### ISSUE TITLE
正文所引用的图片编号，存在不必要的冒号后缀

### ISSUE THREAD

**Issue by realfish** [w3c/clreq#451]
[例](https://w3c.github.io/clreq/#song)，截图如下：

![Screenshot 2022-03-17 at 12 05 20@2x](https://user-images.githubusercontent.com/3247876/158735183-d04f469e-fec6-4faa-af6d-42a2055d882e.png)

**Comment by xfq** [comment]
Removing https://github.com/w3c/clreq/blob/06e20348498c4827279b85541a371169d3eb39d9/local.css#L64-L66 fixes the problem.

Do you know why this was added back then, @r12a?

**Comment by kecrily** [comment]
I think it is used in this context

![image](https://user-images.githubusercontent.com/45708948/158938905-6fe03106-9aa4-4ffa-938e-12d07abff985.png)

**Comment by r12a** [comment]
I think that it used to be generally applied because respec added the caption to the term ref, eg.

![Screenshot 2022-03-18 at 09 44 23](https://user-images.githubusercontent.com/4839211/158979547-50f42620-8e80-4fe7-baeb-ab47df8d600c.png)

But since then respec was changed so that it doesn't show the caption (thankfully), and our CSS is still unchanged. 

As @kecrily points out, i think it's probably needed for actual caption use (at least in English), so would should probably add to the select path so that it's only applied where needed.
