### ISSUE TITLE
title needs to span Chinese text (or possibly English text instead) in title

### ISSUE THREAD

**Issue by aphillips** [w3c/clreq#72]
A colleague (Robert Chu) points out:

> Also, the title needs spans to tag the Chinese text:
> 
> `<h1 property="dcterms:title" id="title" class="title p-name">中文排版需求 Requirements for Chinese Text Layout</h1>`

Going on to note something I eminently agree with:

> W3C documents should be setting a good example =]

**Comment by r12a** [comment]
That, i also want to fix, but it's not straightforward. The h1 heading is generated by respec from the title element, which doesn't take markup.  I intend to ask the respec folks to change respec so that this is not the case. I haven't had the bandwidth to set that in motion as yet, but i will soon.

[start optional academic pontification]
Note however that the actual problem statement shouldn't be "this text isn't marked up for language", but rather "if this text is not marked up for language, then this bad thing happens".  The lang markup is only needed if it's needed, and in this case no-one has yet complained about the Chinese looking strange or failing to work in some way.

(Note, the html tag _should_ always have a lang attribute – and ours does – it's just the lower level declarations i'm talking about, which are there to serve a purpose when it comes to doing something with the text.)

(Note also that i _am_ planning to add language information, but at this point we haven't had the sky falling on our head so we're pushing hard to avoid unnecessary delays in getting the FPWD out of the door. In fact there are several other aspects of markup we need to improve, such as dfn for terms in the chinese, and more of those for the english too.  These things will be addressed as we move forward from FPWD.)
[end of optional academic pontification]

**Comment by r12a** [comment]
fixed by https://github.com/w3c/clreq/commit/1a0a0d24b00074fc6b29c95c974b49e8164a0a77

`lang=zh` is automatically added to all tags with `data-lang=zh`, unless they already have a `lang` attribute.

this may lead to a small amount of temporary mislabelling on the rare occasion where text is supplied in english and awaits a chinese translation, or a lack of lang=zh where a temporary copy of a chinese addition is awaiting an english translation, but that is not a serious issue.

the version of the document published on TR doesn't use the js, as the `lang` attributes are in the markup.  This is because respec produces the TR version from the fully loaded page.
