### ISSUE TITLE
Typo: using full-width parenthesis for Chinese characters

### ISSUE THREAD

**Issue by ryukeikun** [w3c/clreq#74]
A small point and easy to change: I think it is better to use full-width, instead of half-width parenthesis for Chinese characters, e.g. in Editor List.
Eric Q. LIU(刘庆) -> Eric Q. LIU（刘庆）

vice versa, for contents only have ASCII characters, it is better to use half-width parenthesis, e.g.
（GB/T 15834–2011）--> (GB/T 15834–2011)

and, in last paragraph of English translation of section 3.1, the parenthesis are even mis-matched!
（GB/T 15834—2011) --> (GB/T 15834—2011)

**Comment by r12a** [comment]
> and, in last paragraph of English translation of section 3.1, the parenthesis are even mis-matched!
> （GB/T 15834—2011) --> (GB/T 15834—2011) 

fixed by https://github.com/w3c/clreq/commit/1659cb63fa63e28ede4a1673bde65dc22c162334
(btw, if you translate the chinese to english please make a note to convert the parentheses – i guess there must be some keyboard setting involved, because i had to convert pretty much all the parens in all the text i post-edited, and it was easy to miss these three)

> vice versa, for contents only have ASCII characters, it is better to use half-width parenthesis, e.g.
> （GB/T 15834–2011）--> (GB/T 15834–2011)

so that i'm clear, when you say 'half-width parenthesis' do you mean U+0028 LEFT PARENTHESIS and U+0029 RIGHT PARENTHESIS? Its an intriguing suggestion, because that means that the text inside the parentheses dictates the form of the parenthesis. Normally, in my experience, the parentheses are regarded as part of the surrounding text, not the inner text. If we follow this rule, then presumably we would need to change the text in 3.1.1.2 標號, bullet 2, to indicate that this usage also exists?

> I think it is better to use full-width, instead of half-width parenthesis for Chinese characters, e.g. in Editor List.
> Eric Q. LIU(刘庆) -> Eric Q. LIU（刘庆）

this one is a little more tricky. The document is bilingual, but the initial language (what's in the html lang attribute on initial load) is english. I considered what to do about the editor list, and it seemed like overkill to repeat it in both english and chinese (plus that's hard to do with respec). So i opted for an english version.  Note that in the github version there are spaces before the opening parens, which makes it look better.  (i'll raise a separate issue about the name format).
