### ISSUE TITLE
Adding definitions to the glossary

### ISSUE THREAD

**Issue by r12a** [w3c/clreq#78]
@ethantw some points for discussion about converting the glossary to hold linkable definitions, like jlreq:

the glossary currently has the following columns

term | pinyin | english

if we are to add definitions, like for jlreq, we need to add a 'definition' column

i assume that the definition column cells will contain three versions of each definition, en, zh-hans, zh.  Each of which can be filtered out.

do we need the first two columns to be changed to TC term | TC pinyin | SC term | SC pinyin?  Or should we add both TC and SC terms to one column, and pinyin to a second?  If we do that, should we allow the SC vs TC terms/pinyin to be filtered out, or keep them always there?  I think always there.

we also need to add ids to each row. I guess it wouldn't work to base the ids on the pinyin, since we'd ideally want to avoid tone marks so that people have less difficulty constructing links – if we avoid the tone marks, we'll presumably have clashes with some words. So maybe we should base them on the english?

if we have answers to these questions, i can help, if you like, to reconfigure the table markup the next time i get some free time, because i think it is important to sort out the glossary asap.

**Comment by ethantw** [comment]
> if we have answers to these questions, i can help, if you like, to reconfigure the table markup the next time i get some free time, because i think it is important to sort out the glossary asap.

We are currently using the CSV file for sorting out the glossary, so that we can use tools like Excel to edit the content, automatically sort the order by Pinyin or English, and convert the format to HTML (in CLI tools or else). Can we please stay in using this procedures?

**The CSV file:** https://github.com/w3c/clreq/blob/gh-pages/glossary-pinyin.csv

> do we need the first two columns to be changed to TC term | TC pinyin | SC term | SC pinyin? Or should we add both TC and SC terms to one column, and pinyin to a second?

I prefer TC/SC in one column and Pinyin in another.

> If we do that, should we allow the SC vs TC terms/pinyin to be filtered out, or keep them always there? I think always there.

Always there.

> we also need to add ids to each row. I guess it wouldn't work to base the ids on the pinyin, since we'd ideally want to avoid tone marks so that people have less difficulty constructing links – if we avoid the tone marks, we'll presumably have clashes with some words. So maybe we should base them on the english?

I’d say English IDs so that we can maintain the consistency with heading titles and avoid the conflicts of TC and SC.

**Comment by ryukeikun** [comment]
> do we need the first two columns to be changed to TC term | TC pinyin | SC term | SC pinyin? Or should we add both TC and SC terms to one column, and pinyin to a second? If we do that, should we allow the SC vs TC terms/pinyin to be filtered out, or keep them always there? I think always there.

I prefer separate columns than slashes because current clashes is complicated  –– 2 terms are not simply TC/SC terms but sometimes several translations to one term (e.g. 字体设计/字体排印 for typography)，so slashes are complicated and sometimes misleading.

Also, if SC/TC use different terms, pinyin will also different, so I agree to have different column for each of them.

The ordering issue maybe solved technically. But before that I think we can try to first separate them.

And, definition is needed too, also it is a hard work ;-)

**Comment by ethantw** [comment]
Have separated TC/SC to two columns via ccfaa3a now. My next step is to add the definitions according to our meeting last week.

**Comment by r12a** [comment]
thanks @ethantw.  We also need to add ids that will be used for table rows.

**Comment by ethantw** [comment]
Added some Chinese definitions in the glossary via acc85ab2fbb329115df4896455457a23584c2235. It is yet finished. Please review, thanks!

**Comment by ethantw** [comment]
cc:  @bobbytung @ryukeikun,
 Please help to review and improve. ☺️

**Comment by ethantw** [comment]
By the way, I think that the we don't need the definitions to the punctuations since they are well explained in the main content, 3.1.1. The only reason that they exist in the glossary table is to provide the bilingual names.

**Comment by r12a** [comment]
It may help to put links to the definitions of the punctuation.

**Comment by ethantw** [comment]
Done with https://github.com/w3c/clreq/pull/138
